apiVersion: apps/v1
kind: Deployment
metadata:
  name: blueskygreenbuilds-${FINAL_VERSION}
  namespace: eddie
  labels:
    app: blueskygreenbuilds
    version: "${FINAL_VERSION}" #must be string to successfully convert to json read by kubectl.
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /actuator/prometheus
    circleci.com/pipeline-id: "${CIRCLE_PIPELINE_NUM}"
    circleci.com/workflow-id: "${CIRCLE_WORKFLOW_ID}"
    circleci.com/build-number: "${CIRCLE_BUILD_NUM}"
    circleci.com/build-url: "${CIRCLE_BUILD_URL}"
    circleci.com/job-name: "${CIRCLE_JOB}"

spec:
  replicas: 2
  selector:
    matchLabels:
      app: blueskygreenbuilds
      version: "${FINAL_VERSION}"
  template:
    metadata:
      labels:
        app: blueskygreenbuilds
        version: "${FINAL_VERSION}"
    spec:
      containers:
      - name: blueskygreenbuilds
        imagePullPolicy: Always
        image: "${FINAL_IMAGE}" #quoted since it contains colon
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          failureThreshold: 1
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
---
